### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by saber-nyan** [saber-nyan/laszlo-vk-bot#1]
- [x] Завершаемся с ошибкой, если токен не бесконечный/нет прав.
- [x] Меняем закрепленный/выбранный пост каждые `n` дней.
  - [x] Стараемся, чтобы текст не повторялся.
  - [x] Даем дни "передышки".
  - [x] Ловим ошибки, сообщаем о них, пробуем еще раз.
         **ВАЖНО:** чтобы пост не повторялся, шлем запрос вместе с `guid`!
  - [x] Желательно пересмотреть используемый шедулер. Возможно, имеет смысл использовать просто `time.sleep()`.
  - [x] **ВАЖНО:** храним состояние бота на случай краша/перезапуска с помощью `pickle`!
    * Под состоянием имею в виду уже использованные тексты и время следующего поста.
- [ ] Автоматически модерируем комментарии.
  - [ ] Для этого предполагаю использовать [Flask](http://flask.pocoo.org/).
  - [ ] Возможно, `CSON` не совсем подходит для этого всего; посмотреть на альтернативные форматы.
         Есть идея использовать прямо `python`-класс, но будут проблемы с пробелами/табами.
  - [ ] При создании нового комментария проходим по нему лямбдой, указанной в поле `comment_chk`.
    * Передаем в лямбду весь объект `comment`, где есть поле `text`.
    * При возврате `True` из лямбды удаляем комментарий/баним бользователя/етц.

**Comment by tdemin** [comment]
> Есть идея использовать прямо python-класс, но будут проблемы с пробелами/табами.
> В планах — наблюдающий за его ВЫПОЛНЕНИЕМ.

А есть много вариантов реализовать последнее? Так или иначе, пишущему правило придется писать код. Рано или поздно так к мини-скриптам и придешь. Во всяком случае, со сложными правилами так.

**Comment by saber-nyan** [comment]
> А есть много вариантов реализовать последнее?

Вполне. В этом и проблема: надо сбалансировать сложность настройки и гибкость.

На одной стороне простейшее `"test" in str` или регексы, не дающие никакой свободы, но вполне простые в использовании.

На другой же — полноценный обработчик Python-классом. Его сложнее писать человеку, не знакомому с Python или программированием в принципе, но это полная свобода.
***
Вообще, только что появилась идея реализовать оба подхода: в CSON запилить поле `comment_chk` (и класть в него относительный путь к скрипту, ссылку на модуль или писать скрипт прям там? **TODO:** обдумать) и `comment_regex`.
При присутствии же первого поля, оно и используется, а второе игнорируется (или объединяется через `and`? А может быть `or`?)
